-- return {
--   -- Mason
--   {
--     "williamboman/mason.nvim",
--     opts = { ensure_installed = { "markdownlint-cli2", "markdown-toc" } },
--   },
--   -- nvim-lspconfig
--   {
--     "neovim/nvim-lspconfig",
--     opts = {
--       servers = {
--         marksman = {},
--       },
--     },
--   },
--   -- markdown preview via node with version 18
--   {
--     "iamcco/markdown-preview.nvim",
--     cmd = { "MarkdownPreviewToggle", "MarkdownPreview", "MarkdownPreviewStop" },
--     build = function()
--       require("lazy").load({ plugins = { "markdown-preview.nvim" } })
--       vim.fn["mkdp#util#install"]()
--     end,
--     keys = {
--       {
--         "<leader>cp",
--         ft = "markdown",
--         "<cmd>MarkdownPreviewToggle<cr>",
--         desc = "Markdown Preview",
--       },
--     },
--     config = function()
--       vim.cmd([[do FileType]])
--     end,
--   },
--   -- preview markdown in browser
--   { "markdown-preview.nvim" },
--   -- markdown.nvim (Plugin to improve viewing Markdown files in Neovim)
--   {
--     "MeanderingProgrammer/render-markdown.nvim",
--     opts = {
--       code = {
--         sign = false,
--         width = "block",
--         right_pad = 1,
--       },
--       heading = {
--         sign = false,
--         icons = {},
--       },
--     },
--     ft = { "markdown", "norg", "rmd", "org" },
--     config = function(_, opts)
--       require("render-markdown").setup(opts)
--       Snacks.toggle({
--         name = "Render Markdown",
--         get = function()
--           return require("render-markdown.state").enabled
--         end,
--         set = function(enabled)
--           local m = require("render-markdown")
--           if enabled then
--             m.enable()
--           else
--             m.disable()
--           end
--         end,
--       }):map("<leader>um")
--     end,
--   },
-- }
