return {
  {
    "nvim-treesitter/nvim-treesitter",
    opts = {
      ensure_installed = {
        "bash",
        "html",
        "javascript",
        "json",
        "lua",
        "markdown",
        "markdown_inline",
        "python",
        "query",
        "regex",
        "tmux",
        "fish",
        "tsx",
        "typescript",
        "vim",
        "vue",
        "yaml",
        "css",
        "scss",
        "toml",
        "ruby",
        "rust",
        "vue",
        "angular",
        "dockerfile",
      },
    },
  },
}
